site_name: APRSNotify Wiki
site_url: https://n8acl.github.io/aprsnotify
repo_url: https://github.com/n8acl/aprsnotify
theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: 'amber'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Embrace the dark side
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'amber'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Welcome!: index.md
  - About APRSNotify: about.md
  - Project Status Board: https://github.com/users/n8acl/projects/3/views/1
  - Supported Services: supported_services.md
  - Getting Started: 
    - Installation/Setup:
        - Getting Started: getting_started.md
        - Migrating: migration.md
        - Manual Installation: install.md
        - Docker Installation (recommended): docker.md
    - Configuration:
        - Configuration Utility Guide: configuration_guide.md
  - Changes:
    - Revision Explaination: revision_explaination.md
    - Change Log (changes prior to 2024): changelog.md

