name: discord message on clone
on: [clone]
jobs:

 notify:
    name: Notify_Discord
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: Ilshidur/action-discord@master
      with:
        args: APRSNotify - Someone Cloned the repo.
